name = "one"
type = "webpack"
workers_dev = true
account_id = "2912a37c7c764ca29d9dd889f8176d5e"
zone_id = "81db3deea44e5a3899851f6b3ec34d76"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "", id = "540f06ae6ad7448ca63e4ad6f4a33532" }
]

[env.staging]
name = "drive-staging"
